name: hubspot_example
description: "Demonstrates how to use the hubspot plugin."
version: 1.0.0+001
publish_to: 'none'

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  hubspot:
    path: ../

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  disable-swift-package-manager: false