name: hubspot_flutter
description: "A new Flutter plugin project."
version: 0.0.1
homepage: https://github.com/shuttlershq/hubspot_flutter
repository: https://github.com/shuttlershq/hubspot_flutter
issue_tracker: https://github.com/shuttlershq/hubspot_flutter/issues
documentation: https://github.com/shuttlershq/hubspot_flutter/blob/dev/README.md
topics:
  - hubspot
  - support
  - chat-widget

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: co.shuttlers.hubspot_flutter
        pluginClass: HubspotFlutterPlugin
      ios:
        pluginClass: HubspotFlutterPlugin
        disable-swift-package-manager: false